title: Introduction to SQL
tagline: Store your data in a versatile robust manner.
description: >-
  In this course you''ll learn how to create a table, insert data, and query
  those data..
template:
  name: lab-hello-sql
  repo: false
before:
  - type: respond
    with: 01_first-response.md
steps:
  - actions:
      - else:
          - type: respond
            with: 01_try-again.md
        left: '%payload.pull_request.base.ref%'
        operator: ===
        right: master
        type: gate
      - type: respond
        with: 01_nice-work.md
    description: Use SQL to create a table with a few colums
    event: pull_request.synchronize
    title: Create your first table
